### ISSUE TITLE
RSS 文件似乎有问题

### ISSUE THREAD

**Issue by XiangyunHuang** [JackieMium/netlify.blog#2]
<img width="812" alt="截屏2022-06-30 13 38 48" src="https://user-images.githubusercontent.com/12031874/176601021-89c61d9a-16fc-4013-bfd8-e4983c563bf4.png">

当点击 RSS 订阅图标，跳转到 <http://localhost:1313/index.xml> 了

**Comment by JackieMium** [comment]
> 当点击 RSS 订阅图标，跳转到 http://localhost:1313/index.xml 了

谢谢，hotfix 了  https://github.com/JackieMium/netlify.blog/commit/9b3b318116e604c156d8c62470035a4762d659b8

**Comment by XiangyunHuang** [comment]
不客气。
